name: CI

on:
  push:
    branches:
      - main
      - ci
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
      - cron: '0 0 * * 0'
          
jobs:
  moonshot:
    env:
      CUDA_VISIBLE_DEVICES: 1
      JULIA_DEPOT_PATH: /scratch/github-actions/julia_depot
      DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-22.04]
        julia-version: ['1.10']
        julia-arch: [x64]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
